
from functools import partial
from enum import Enum

def no_parser(x):
    return x

class MetricType(Enum):
    COUNTER = 1
    GAUGE = 2
    STRING = 3

    def lookup_fn(self, conn):
        if self.value is self.COUNTER.value or self.value is self.GAUGE.value:
            return conn.integer
        elif self.value is self.STRING.value:
            return conn.blob
        else:
            raise RuntimeError("Invalid value: ", str(self))

METRICS = {'cpu.idle': {'type': MetricType.COUNTER,
                        'unit': 'Nanoseconds',
                        'parser': no_parser},
           'cpu.system': {'type': MetricType.COUNTER,
                          'unit': 'Nanoseconds',
                          'parser': no_parser},
           'cpu.user': {'type': MetricType.COUNTER,
                        'unit': 'Nanoseconds',
                        'parser': no_parser},
           'disk.bytes_free': {'type': MetricType.GAUGE,
                               'unit': 'Bytes'},
           'disk.bytes_total': {'type': MetricType.GAUGE,
                                'unit': 'Bytes'},
           'disk.path': {'type': MetricType.STRING,
                         'unit': None},
           'engine_build_date': {'type': MetricType.STRING,
                                 'unit': None},
           'engine_version': {'type': MetricType.STRING,
                              'unit': None},
           'hardware_concurrency': {'type': MetricType.GAUGE,
                                    'unit': 'Count'},
           'memory.bytes_resident_size': {'type': MetricType.GAUGE,
                                          'unit': 'Bytes'},
           'memory.physmem.bytes_total': {'type': MetricType.GAUGE,
                                          'unit': 'Bytes'},
           'memory.physmem.bytes_used': {'type': MetricType.GAUGE,
                                         'unit': 'Bytes'},
           'memory.resident_count': {'type': MetricType.GAUGE,
                                     'unit': 'Count'},
           'memory.vm.bytes_total': {'type': MetricType.GAUGE,
                                     'unit': 'Bytes'},
           'memory.vm.bytes_used': {'type': MetricType.GAUGE,
                                    'unit': 'Bytes'},
           'network.current_users_count': {'type': MetricType.GAUGE,
                                           'unit': 'Count'},
           'network.sessions.available_count': {'type': MetricType.GAUGE,
                                                'unit': 'Count'},
           'network.sessions.max_count': {'type': MetricType.GAUGE,
                                          'unit': 'Count'},
           'network.sessions.unavailable_count': {'type': MetricType.GAUGE,
                                                  'unit': 'Count'},
           'node_id': {'type': MetricType.STRING,
                       'unit': None},
           'operating_system': {'type': MetricType.STRING,
                                'unit': None},
           'partitions_count': {'type': MetricType.GAUGE,
                                'unit': 'Count'},
           'evictions_count': {'type': MetricType.COUNTER,
                               'unit': 'Count'},
           'perf.blob.update.content_writing.total_ns': {'type': MetricType.COUNTER,
                                                         'unit': 'Nanoseconds',
                                                         'parser': no_parser},
           'perf.blob.update.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                         'unit': 'Nanoseconds',
                                                         'parser': no_parser},
           'perf.blob.update.entry_trimming.total_ns': {'type': MetricType.COUNTER,
                                                        'unit': 'Nanoseconds',
                                                        'parser': no_parser},
           'perf.blob.update.entry_writing.total_ns': {'type': MetricType.COUNTER,
                                                       'unit': 'Nanoseconds',
                                                       'parser': no_parser},
           'perf.blob.update.processing.total_ns': {'type': MetricType.COUNTER,
                                                    'unit': 'Nanoseconds',
                                                    'parser': no_parser},
           'perf.common.count_by_affix.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                   'unit': 'Nanoseconds',
                                                                   'parser': no_parser},
           'perf.common.count_by_affix.processing.total_ns': {'type': MetricType.COUNTER,
                                                              'unit': 'Nanoseconds',
                                                              'parser': no_parser},
           'perf.common.get.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                        'unit': 'Nanoseconds',
                                                        'parser': no_parser},
           'perf.common.get.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                        'unit': 'Nanoseconds',
                                                        'parser': no_parser},
           'perf.common.get.processing.total_ns': {'type': MetricType.COUNTER,
                                                   'unit': 'Nanoseconds',
                                                   'parser': no_parser},
           'perf.common.remove.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.common.remove.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.common.remove.entry_writing.total_ns': {'type': MetricType.COUNTER,
                                                         'unit': 'Nanoseconds',
                                                         'parser': no_parser},
           'perf.common.remove.processing.total_ns': {'type': MetricType.COUNTER,
                                                      'unit': 'Nanoseconds',
                                                      'parser': no_parser},
           'perf.common.get_acl.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.common.get_acl.processing.total_ns': {'type': MetricType.COUNTER,
                                                       'unit': 'Nanoseconds',
                                                       'parser': no_parser},
           'perf.common.get_by_affix.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                              'unit': 'Nanoseconds',
                                                              'parser': no_parser},
           'perf.common.get_by_affix.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.common.get_by_affix.processing.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.common.get_by_type.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                              'unit': 'Nanoseconds',
                                                              'parser': no_parser},
           'perf.common.get_by_type.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.common.get_by_type.processing.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.common.get_metadata.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.common.get_metadata.processing.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.common.get_range.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                              'unit': 'Nanoseconds',
                                                              'parser': no_parser},
           'perf.common.get_range.processing.total_ns': {'type': MetricType.COUNTER,
                                                         'unit': 'Nanoseconds',
                                                         'parser': no_parser},
           'perf.common.get_versions.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.common.get_versions.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.common.get_versions.processing.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.common.set_transaction_state.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                                          'unit': 'Nanoseconds',
                                                                          'parser': no_parser},
           'perf.common.set_transaction_state.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                          'unit': 'Nanoseconds',
                                                                          'parser': no_parser},
           'perf.common.set_transaction_state.entry_trimming.total_ns': {'type': MetricType.COUNTER,
                                                                         'unit': 'Nanoseconds',
                                                                         'parser': no_parser},
           'perf.common.set_transaction_state.entry_writing.total_ns': {'type': MetricType.COUNTER,
                                                                        'unit': 'Nanoseconds',
                                                                        'parser': no_parser},
           'perf.common.set_transaction_state.processing.total_ns': {'type': MetricType.COUNTER,
                                                                     'unit': 'Nanoseconds',
                                                                     'parser': no_parser},
           'perf.control.system.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.control.system.processing.total_ns': {'type': MetricType.COUNTER,
                                                       'unit': 'Nanoseconds',
                                                       'parser': no_parser},
           'perf.control.status.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.control.status.processing.total_ns': {'type': MetricType.COUNTER,
                                                       'unit': 'Nanoseconds',
                                                       'parser': no_parser},
           'perf.control.trim_all.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                              'unit': 'Nanoseconds',
                                                              'parser': no_parser},
           'perf.control.trim_all.processing.total_ns': {'type': MetricType.COUNTER,
                                                         'unit': 'Nanoseconds',
                                                         'parser': no_parser},
           'perf.integer.update.content_writing.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.integer.update.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.integer.update.entry_trimming.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.integer.update.entry_writing.total_ns': {'type': MetricType.COUNTER,
                                                          'unit': 'Nanoseconds',
                                                          'parser': no_parser},
           'perf.integer.update.processing.total_ns': {'type': MetricType.COUNTER,
                                                       'unit': 'Nanoseconds',
                                                       'parser': no_parser},
           'perf.placeholder.put.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                             'unit': 'Nanoseconds',
                                                             'parser': no_parser},
           'perf.placeholder.put.entry_writing.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.placeholder.put.entry_trimming.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.placeholder.put.processing.total_ns': {'type': MetricType.COUNTER,
                                                        'unit': 'Nanoseconds',
                                                        'parser': no_parser},
           'perf.tag.leaf_insert.entry_trimming.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.tag.leaf_insert.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                             'unit': 'Nanoseconds',
                                                             'parser': no_parser},
           'perf.tag.leaf_insert.entry_writing.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.tag.leaf_insert.processing.total_ns': {'type': MetricType.COUNTER,
                                                        'unit': 'Nanoseconds',
                                                        'parser': no_parser},
           'perf.ts.aggregate_table.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                             'unit': 'Nanoseconds',
                                                             'parser': no_parser},
           'perf.ts.aggregate_table.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                                'unit': 'Nanoseconds',
                                                                'parser': no_parser},
           'perf.ts.aggregate_table.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                'unit': 'Nanoseconds',
                                                                'parser': no_parser},
           'perf.ts.aggregate_table.directory_reading.total_ns': {'type': MetricType.COUNTER,
                                                                  'unit': 'Nanoseconds',
                                                                  'parser': no_parser},
           'perf.ts.aggregate_table.processing.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.ts.aggregate_table.serialization.total_ns': {'type': MetricType.COUNTER,
                                                              'unit': 'Nanoseconds',
                                                              'parser': no_parser},

           'perf.ts.apply_bitmap.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                          'unit': 'Nanoseconds',
                                                          'parser': no_parser},
           'perf.ts.apply_bitmap.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                             'unit': 'Nanoseconds',
                                                             'parser': no_parser},
           'perf.ts.apply_bitmap.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                             'unit': 'Nanoseconds',
                                                             'parser': no_parser},
           'perf.ts.apply_bitmap.directory_reading.total_ns': {'type': MetricType.COUNTER,
                                                               'unit': 'Nanoseconds',
                                                               'parser': no_parser},
           'perf.ts.apply_bitmap.processing.total_ns': {'type': MetricType.COUNTER,
                                                        'unit': 'Nanoseconds',
                                                        'parser': no_parser},
           'perf.ts.apply_bitmap.serialization.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.ts.apply_bitmap_and_aggregate.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                                        'unit': 'Nanoseconds',
                                                                        'parser': no_parser},
           'perf.ts.apply_bitmap_and_aggregate.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                                           'unit': 'Nanoseconds',
                                                                           'parser': no_parser},
           'perf.ts.apply_bitmap_and_aggregate.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                           'unit': 'Nanoseconds',
                                                                           'parser': no_parser},
           'perf.ts.apply_bitmap_and_aggregate.directory_reading.total_ns': {'type': MetricType.COUNTER,
                                                                             'unit': 'Nanoseconds',
                                                                             'parser': no_parser},
           'perf.ts.apply_bitmap_and_aggregate.processing.total_ns': {'type': MetricType.COUNTER,
                                                                      'unit': 'Nanoseconds',
                                                                      'parser': no_parser},
           'perf.ts.apply_bitmap_and_aggregate.serialization.total_ns': {'type': MetricType.COUNTER,
                                                                         'unit': 'Nanoseconds',
                                                                         'parser': no_parser},

           'perf.ts.blob_aggregate.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.blob_aggregate.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                               'unit': 'Nanoseconds',
                                                               'parser': no_parser},
           'perf.ts.blob_aggregate.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.ts.blob_aggregate.directory_reading.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.ts.blob_aggregate.processing.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.blob_aggregate.serialization.total_ns': {'type': MetricType.COUNTER,
                                                             'unit': 'Nanoseconds',
                                                             'parser': no_parser},
           'perf.ts.blob_insert.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.blob_insert.content_writing.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.blob_insert.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.blob_insert.directory_writing.total_ns': {'type': MetricType.COUNTER,
                                                              'unit': 'Nanoseconds',
                                                              'parser': no_parser},
           'perf.ts.blob_insert.entry_trimming.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.ts.blob_insert.entry_writing.total_ns': {'type': MetricType.COUNTER,
                                                          'unit': 'Nanoseconds',
                                                          'parser': no_parser},
           'perf.ts.blob_insert.processing.total_ns': {'type': MetricType.COUNTER,
                                                       'unit': 'Nanoseconds',
                                                       'parser': no_parser},
           'perf.ts.blob_insert.ts_bucket_updating.total_ns': {'type': MetricType.COUNTER,
                                                               'unit': 'Nanoseconds',
                                                               'parser': no_parser},
           'perf.ts.create_root.content_writing.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.create_root.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.create_root.entry_writing.total_ns': {'type': MetricType.COUNTER,
                                                          'unit': 'Nanoseconds',
                                                          'parser': no_parser},
           'perf.ts.create_root.entry_trimming.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.ts.create_root.processing.total_ns': {'type': MetricType.COUNTER,
                                                       'unit': 'Nanoseconds',
                                                       'parser': no_parser},
           'perf.ts.double_aggregate.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                              'unit': 'Nanoseconds',
                                                              'parser': no_parser},
           'perf.ts.double_aggregate.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.ts.double_aggregate.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.ts.double_aggregate.directory_reading.total_ns': {'type': MetricType.COUNTER,
                                                                   'unit': 'Nanoseconds',
                                                                   'parser': no_parser},
           'perf.ts.double_aggregate.processing.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.double_aggregate.serialization.total_ns': {'type': MetricType.COUNTER,
                                                               'unit': 'Nanoseconds',
                                                               'parser': no_parser},
           'perf.ts.erase_range.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                         'unit': 'Nanoseconds',
                                                         'parser': no_parser},
           'perf.ts.erase_range.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.erase_range.content_writing.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.erase_range.directory_writing.total_ns': {'type': MetricType.COUNTER,
                                                              'unit': 'Nanoseconds',
                                                              'parser': no_parser},
           'perf.ts.erase_range.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.erase_range.entry_trimming.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.ts.erase_range.entry_writing.total_ns': {'type': MetricType.COUNTER,
                                                          'unit': 'Nanoseconds',
                                                          'parser': no_parser},
           'perf.ts.erase_range.processing.total_ns': {'type': MetricType.COUNTER,
                                                       'unit': 'Nanoseconds',
                                                       'parser': no_parser},
           'perf.ts.erase_range.serialization.total_ns': {'type': MetricType.COUNTER,
                                                          'unit': 'Nanoseconds',
                                                          'parser': no_parser},
           'perf.ts.evaluate_expression.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.ts.evaluate_expression.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                                    'unit': 'Nanoseconds',
                                                                    'parser': no_parser},
           'perf.ts.evaluate_expression.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                    'unit': 'Nanoseconds',
                                                                    'parser': no_parser},
           'perf.ts.evaluate_expression.directory_reading.total_ns': {'type': MetricType.COUNTER,
                                                                      'unit': 'Nanoseconds',
                                                                      'parser': no_parser},
           'perf.ts.evaluate_expression.processing.total_ns': {'type': MetricType.COUNTER,
                                                               'unit': 'Nanoseconds',
                                                               'parser': no_parser},
           'perf.ts.evaluate_expression.serialization.total_ns': {'type': MetricType.COUNTER,
                                                                  'unit': 'Nanoseconds',
                                                                  'parser': no_parser},
           'perf.ts.evaluate_expression.ts_evaluating.total_ns': {'type': MetricType.COUNTER,
                                                                  'unit': 'Nanoseconds',
                                                                  'parser': no_parser},
           'perf.ts.get_column_info.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                                'unit': 'Nanoseconds',
                                                                'parser': no_parser},
           'perf.ts.get_column_info.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                'unit': 'Nanoseconds',
                                                                'parser': no_parser},
           'perf.ts.get_column_info.processing.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.ts.get_columns.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.get_columns.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.get_columns.processing.total_ns': {'type': MetricType.COUNTER,
                                                       'unit': 'Nanoseconds',
                                                       'parser': no_parser},
           'perf.ts.get_range.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                       'unit': 'Nanoseconds',
                                                       'parser': no_parser},
           'perf.ts.get_range.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                          'unit': 'Nanoseconds',
                                                          'parser': no_parser},
           'perf.ts.get_range.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                          'unit': 'Nanoseconds',
                                                          'parser': no_parser},
           'perf.ts.get_range.directory_reading.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.get_range.processing.total_ns': {'type': MetricType.COUNTER,
                                                     'unit': 'Nanoseconds',
                                                     'parser': no_parser},
           'perf.ts.get_range.serialization.total_ns': {'type': MetricType.COUNTER,
                                                        'unit': 'Nanoseconds',
                                                        'parser': no_parser},
           'perf.ts.int64_aggregate.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                             'unit': 'Nanoseconds',
                                                             'parser': no_parser},
           'perf.ts.int64_aggregate.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                                'unit': 'Nanoseconds',
                                                                'parser': no_parser},
           'perf.ts.int64_aggregate.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                'unit': 'Nanoseconds',
                                                                'parser': no_parser},
           'perf.ts.int64_aggregate.directory_reading.total_ns': {'type': MetricType.COUNTER,
                                                                  'unit': 'Nanoseconds',
                                                                  'parser': no_parser},
           'perf.ts.int64_aggregate.processing.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.ts.int64_aggregate.serialization.total_ns': {'type': MetricType.COUNTER,
                                                              'unit': 'Nanoseconds',
                                                              'parser': no_parser},
           'perf.ts.table_insert.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                             'unit': 'Nanoseconds',
                                                             'parser': no_parser},
           'perf.ts.table_insert.content_writing.total_ns': {'type': MetricType.COUNTER,
                                                             'unit': 'Nanoseconds',
                                                             'parser': no_parser},
           'perf.ts.table_insert.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                             'unit': 'Nanoseconds',
                                                             'parser': no_parser},
           'perf.ts.table_insert.directory_writing.total_ns': {'type': MetricType.COUNTER,
                                                               'unit': 'Nanoseconds',
                                                               'parser': no_parser},
           'perf.ts.table_insert.entry_trimming.total_ns': {'type': MetricType.COUNTER,
                                                            'unit': 'Nanoseconds',
                                                            'parser': no_parser},
           'perf.ts.table_insert.entry_writing.total_ns': {'type': MetricType.COUNTER,
                                                           'unit': 'Nanoseconds',
                                                           'parser': no_parser},
           'perf.ts.table_insert.processing.total_ns': {'type': MetricType.COUNTER,
                                                        'unit': 'Nanoseconds',
                                                        'parser': no_parser},
           'perf.ts.timestamp_aggregate.affix_search.total_ns': {'type': MetricType.COUNTER,
                                                                 'unit': 'Nanoseconds',
                                                                 'parser': no_parser},
           'perf.ts.timestamp_aggregate.content_reading.total_ns': {'type': MetricType.COUNTER,
                                                                    'unit': 'Nanoseconds',
                                                                    'parser': no_parser},
           'perf.ts.timestamp_aggregate.deserialization.total_ns': {'type': MetricType.COUNTER,
                                                                    'unit': 'Nanoseconds',
                                                                    'parser': no_parser},
           'perf.ts.timestamp_aggregate.directory_reading.total_ns': {'type': MetricType.COUNTER,
                                                                      'unit': 'Nanoseconds',
                                                                      'parser': no_parser},
           'perf.ts.timestamp_aggregate.processing.total_ns': {'type': MetricType.COUNTER,
                                                               'unit': 'Nanoseconds',
                                                               'parser': no_parser},
           'perf.ts.timestamp_aggregate.serialization.total_ns': {'type': MetricType.COUNTER,
                                                                  'unit': 'Nanoseconds',
                                                                  'parser': no_parser},
           'persistence.bytes_capacity': {'type': MetricType.GAUGE,
                                          'unit': 'Bytes'},
           'persistence.bytes_read': {'type': MetricType.COUNTER,
                                      'unit': 'Bytes'},
           'persistence.bytes_utilized': {'type': MetricType.GAUGE,
                                          'unit': 'Bytes'},
           'persistence.bytes_written': {'type': MetricType.COUNTER,
                                         'unit': 'Bytes'},
           'persistence.entries_count': {'type': MetricType.GAUGE,
                                         'unit': 'Count'},
           'requests.bytes_out': {'type': MetricType.COUNTER,
                                  'unit': 'Bytes'},
           'requests.errors_count': {'type': MetricType.COUNTER,
                                     'unit': 'Count'},
           'requests.successes_count': {'type': MetricType.COUNTER,
                                        'unit': 'Count'},
           'requests.total_count': {'type': MetricType.COUNTER,
                                    'unit': 'Count'},
           'startup': {'type': MetricType.COUNTER,
                       'unit': 'None'}}

def key_to_metric(x):
    try:
        return METRICS[x]
    except KeyError:
        print("unrecognized key: ", x)
